### ISSUE TITLE
Can I replace static method?

### ISSUE THREAD

**Issue by blackpost38** [php-mock/php-mock#15]
Hi, guy!

I want to replace my static method by using `setName`.
But I think It can't be static method, right?
If YES, I want to have some advice. 
there is sample code below.
I'll wait for answer.

thanks!

```
    // foo\bar::doSomething() is replaced with 'Yepppp!'
    $builder = new \phpmock\MockBuilder();
    $builder->setNamespace('foo')
            ->setName('doSomething')
            ->setFunction(function () {
                return 'Yepppp!!';
            });
    $mock = $builder->build();
    $mock->enable();
```

**Comment by malkusch** [comment]
> But I think It can't be static method, right?

This library can just mock functions. Static class methods can't be mocked.

**Comment by blackpost38** [comment]
oh, I got it! thanks for your response and awesome library :)
