### ISSUE TITLE
PHP 7 Return Types

### ISSUE THREAD

**Issue by jmauerhan** [php-mock/php-mock#16]
It looks like Mockery is not working with the new PHP 7 Return Types. 

If I have an method with a return type:

```php
<?php

namespace Game\Repository;

use Game\Entity\UserInterface;

Interface UserRepositoryInterface
{
    public function createNewUser($username, $password, $email):UserInterface;
}
```

And I mock it: `$userDummy         = Mockery::mock('Game\Entity\UserInterface');`

I get this error:

```
PHP Fatal error:  Declaration of 
Mockery_2_Game_Repository_UserRepositoryInterface::createNewUser($username, $password, $email) 
must be compatible with 
Game\Repository\UserRepositoryInterface::createNewUser($username, $password, $email): Game\Entity\UserInterface 
in ***\vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 25                
```

If I take the return type off, Mockery works again. Mockery's php version says ">=5.5" so I was hoping it would work with 7 :)

**Comment by malkusch** [comment]
I guess you confused the github project.

**Comment by jmauerhan** [comment]
I did, I'm so sorry, not sure how that happened...I was looking *at* the right one when I started :) Sorry for the trouble!
