### ISSUE TITLE
Searching new maintainer

### ISSUE THREAD

**Issue by malkusch** [php-mock/php-mock#20]
This project and (and those related towards it) searches for a new maintainer. Please volunteer.

**Comment by webimpress** [comment]
@malkusch I can help if you don't have any other candidates

**Comment by malkusch** [comment]
Thank you very much. You're in now.

**Comment by epdenouden** [comment]
@malkusch I'd be interested, too! 🛠

**Comment by malkusch** [comment]
@webimpress is the new maintainer he can add you too to organization if he's interested.

**Comment by epdenouden** [comment]
That's good to hear! I'll focus on PHPUnit then :)

**Comment by webimpress** [comment]
@epdenouden, thanks!
