### ISSUE TITLE
Deprecation Notice with Composer >= 1.10

### ISSUE THREAD

**Issue by BafS** [php-mock/php-mock#33]
I have the last php-mock version but I get this notice when `composer i -o`:

`
Deprecation Notice: Class phpmock\test\MockNamespaceTest located in ./vendor/php-mock/php-mock/tests/MockNamespaceTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by hhovakimyan** [comment]
This pull request solves the issue you described https://github.com/php-mock/php-mock/pull/34.
